"""empty message

Revision ID: 2fcadfa1f6
Revises: f342651dc0
Create Date: 2015-03-03 17:15:07.834960

"""

# revision identifiers, used by Alembic.
revision = '2fcadfa1f6'
down_revision = 'f342651dc0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('passwd', sa.String(length=60), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('sex', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
