"""empty message

Revision ID: f342651dc0
Revises: None
Create Date: 2015-03-03 17:11:44.146484

"""

# revision identifiers, used by Alembic.
revision = 'f342651dc0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
